"""Migration integrity, exercised by running Alembic against a real database.

A migration that only ever runs forward on a developer's machine is untested.
These run upgrade, downgrade and upgrade again on a scratch database, and assert
the resulting schema matches the ORM metadata.
"""

from __future__ import annotations

import asyncio
from pathlib import Path

import pytest
from alembic import command
from alembic.config import Config
from sqlalchemy import text
from sqlalchemy.ext.asyncio import create_async_engine

from conftest import requires_database
from vyraxis.storage.models import Base

pytestmark = [pytest.mark.integration, requires_database]

REPO_ROOT = Path(__file__).resolve().parents[2]

EXPECTED_TABLES = {
    "ingest_checkpoints",
    "market_events",
    "observations",
    "pools",
    "provider_health_snapshots",
    "system_events",
    "tokens",
    "wallets",
}


def alembic_config(dsn: str) -> Config:
    config = Config(str(REPO_ROOT / "alembic.ini"))
    config.attributes["dsn"] = dsn
    config.attributes["configure_logger"] = False
    return config


@pytest.fixture
def scratch_dsn(settings) -> str:
    """A throwaway database so migrations never touch the shared test schema."""
    base = settings.database.dsn
    root, _, _ = base.rpartition("/")
    name = "vyraxis_migration_scratch"

    async def recreate() -> None:
        admin = create_async_engine(f"{root}/postgres", isolation_level="AUTOCOMMIT")
        try:
            async with admin.connect() as conn:
                await conn.execute(text(f'DROP DATABASE IF EXISTS "{name}" WITH (FORCE)'))
                await conn.execute(text(f'CREATE DATABASE "{name}"'))
        finally:
            await admin.dispose()

    asyncio.run(recreate())
    yield f"{root}/{name}"

    async def drop() -> None:
        admin = create_async_engine(f"{root}/postgres", isolation_level="AUTOCOMMIT")
        try:
            async with admin.connect() as conn:
                await conn.execute(text(f'DROP DATABASE IF EXISTS "{name}" WITH (FORCE)'))
        finally:
            await admin.dispose()

    asyncio.run(drop())


def test_upgrade_creates_every_table(scratch_dsn: str) -> None:
    config = alembic_config(scratch_dsn)
    command.upgrade(config, "head")

    async def inspect() -> set[str]:
        engine = create_async_engine(scratch_dsn)
        try:
            async with engine.connect() as conn:
                result = await conn.execute(
                    text(
                        "SELECT table_name FROM information_schema.tables "
                        "WHERE table_schema = 'public'"
                    )
                )
                return {row[0] for row in result}
        finally:
            await engine.dispose()

    tables = asyncio.run(inspect())
    assert EXPECTED_TABLES.issubset(tables)
    assert "alembic_version" in tables


def test_downgrade_and_upgrade_round_trip(scratch_dsn: str) -> None:
    config = alembic_config(scratch_dsn)
    command.upgrade(config, "head")
    command.downgrade(config, "base")

    async def remaining() -> set[str]:
        engine = create_async_engine(scratch_dsn)
        try:
            async with engine.connect() as conn:
                result = await conn.execute(
                    text(
                        "SELECT table_name FROM information_schema.tables "
                        "WHERE table_schema = 'public'"
                    )
                )
                return {row[0] for row in result}
        finally:
            await engine.dispose()

    assert not EXPECTED_TABLES & asyncio.run(remaining())
    command.upgrade(config, "head")
    assert EXPECTED_TABLES.issubset(asyncio.run(remaining()))


def test_migrated_schema_matches_the_orm_metadata(scratch_dsn: str) -> None:
    """Drift between models and migrations is a silent production outage."""
    from alembic.util.exc import AutogenerateDiffsDetected

    config = alembic_config(scratch_dsn)
    command.upgrade(config, "head")
    try:
        command.check(config)
    except AutogenerateDiffsDetected as exc:  # pragma: no cover - failure path
        pytest.fail(f"schema drift between models and migrations: {exc}")


def test_declared_tables_match_expectations() -> None:
    assert set(Base.metadata.tables) == EXPECTED_TABLES


def test_unique_and_foreign_key_constraints_exist(scratch_dsn: str) -> None:
    config = alembic_config(scratch_dsn)
    command.upgrade(config, "head")

    async def constraints() -> dict[str, set[str]]:
        engine = create_async_engine(scratch_dsn)
        try:
            async with engine.connect() as conn:
                result = await conn.execute(
                    text(
                        # contype is PostgreSQL's "char" type; asyncpg returns it as bytes, so
                        # cast in SQL rather than decoding at the call site.
                        "SELECT contype::text, conname FROM pg_constraint "
                        "WHERE connamespace = 'public'::regnamespace"
                    )
                )
                grouped: dict[str, set[str]] = {}
                for contype, conname in result:
                    grouped.setdefault(contype, set()).add(conname)
                return grouped
        finally:
            await engine.dispose()

    grouped = asyncio.run(constraints())
    # Foreign keys tying events and observations to tokens/pools.
    assert any("market_events" in name for name in grouped.get("f", set()))
    assert any("observations" in name for name in grouped.get("f", set()))
    # Enum CHECK constraints created by string_enum().
    assert any("event_kind" in name for name in grouped.get("c", set()))
    # Uniques for natural keys.
    assert any("tokens" in name for name in grouped.get("u", set()))
