"""alert rules and events

Revision ID: 131cd2bbc4f4
Revises: 2f065e542a7c
Create Date: 2026-08-14 21:26:50.412897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '131cd2bbc4f4'
down_revision: Union[str, Sequence[str], None] = '2f065e542a7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ticker_symbol', sa.String(length=16), nullable=False),
    sa.Column('condition_type', sa.String(length=24), nullable=False),
    sa.Column('comparison', sa.String(length=8), nullable=False),
    sa.Column('threshold_value', sa.Float(), nullable=True),
    sa.Column('target_status', sa.String(length=32), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_fired_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("comparison IN ('above', 'below', 'equals')", name='ck_alert_rule_comparison'),
    sa.CheckConstraint("condition_type IN ('price', 'ai_score', 'manipulation_risk', 'signal_status')", name='ck_alert_rule_condition_type'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alert_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alert_rules_ticker_symbol'), ['ticker_symbol'], unique=False)
        batch_op.create_index('ix_alert_rules_user_active', ['user_id', 'is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_rules_user_id'), ['user_id'], unique=False)

    op.create_table('alert_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ticker_symbol', sa.String(length=16), nullable=False),
    sa.Column('fired_at', sa.DateTime(), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=False),
    sa.Column('observed_value', sa.Float(), nullable=True),
    sa.Column('observed_status', sa.String(length=32), nullable=True),
    sa.Column('acknowledged', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['alert_rules.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alert_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alert_events_fired_at'), ['fired_at'], unique=False)
        batch_op.create_index('ix_alert_events_rule_fired', ['rule_id', 'fired_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_events_rule_id'), ['rule_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_events_ticker_symbol'), ['ticker_symbol'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_events_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alert_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alert_events_user_id'))
        batch_op.drop_index(batch_op.f('ix_alert_events_ticker_symbol'))
        batch_op.drop_index(batch_op.f('ix_alert_events_rule_id'))
        batch_op.drop_index('ix_alert_events_rule_fired')
        batch_op.drop_index(batch_op.f('ix_alert_events_fired_at'))

    op.drop_table('alert_events')
    with op.batch_alter_table('alert_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alert_rules_user_id'))
        batch_op.drop_index('ix_alert_rules_user_active')
        batch_op.drop_index(batch_op.f('ix_alert_rules_ticker_symbol'))

    op.drop_table('alert_rules')
    # ### end Alembic commands ###
