"""baseline schema

Revision ID: 6bbad53f77a7
Revises: 
Create Date: 2026-07-11 15:32:10.132406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bbad53f77a7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backtest_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('strategy_config', sa.JSON(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('sharpe_ratio', sa.Float(), nullable=False),
    sa.Column('sortino_ratio', sa.Float(), nullable=False),
    sa.Column('max_drawdown_pct', sa.Float(), nullable=False),
    sa.Column('profit_factor', sa.Float(), nullable=False),
    sa.Column('expectancy', sa.Float(), nullable=False),
    sa.Column('win_rate', sa.Float(), nullable=False),
    sa.Column('avg_hold_time_days', sa.Float(), nullable=False),
    sa.Column('total_return_pct', sa.Float(), nullable=False),
    sa.Column('num_trades', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_key', sa.String(length=64), nullable=False),
    sa.Column('ticker_symbol', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_sessions_session_key'), ['session_key'], unique=True)

    op.create_table('edgar_company_facts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker_symbol', sa.String(length=16), nullable=False),
    sa.Column('cik', sa.String(length=10), nullable=False),
    sa.Column('shares_outstanding_latest', sa.Float(), nullable=True),
    sa.Column('shares_outstanding_year_ago', sa.Float(), nullable=True),
    sa.Column('dilution_12m_pct', sa.Float(), nullable=True),
    sa.Column('last_filing_date', sa.DateTime(), nullable=True),
    sa.Column('last_periodic_form', sa.String(length=16), nullable=True),
    sa.Column('filing_delinquent', sa.Boolean(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('edgar_company_facts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_edgar_company_facts_ticker_symbol'), ['ticker_symbol'], unique=True)

    op.create_table('model_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('model_type', sa.String(length=32), nullable=False),
    sa.Column('trained_at', sa.DateTime(), nullable=False),
    sa.Column('artifact_path', sa.String(length=255), nullable=False),
    sa.Column('training_metrics', sa.JSON(), nullable=False),
    sa.Column('hyperparameters', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('news_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker_symbol', sa.String(length=16), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('headline', sa.String(length=512), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('sentiment', sa.Float(), nullable=False),
    sa.Column('is_press_release', sa.Boolean(), nullable=False),
    sa.Column('is_promotional', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('news_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_news_items_published_at'), ['published_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_news_items_ticker_symbol'), ['ticker_symbol'], unique=False)
        batch_op.create_index('ix_news_ticker_published', ['ticker_symbol', 'published_at'], unique=False)

    op.create_table('portfolio_positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker_symbol', sa.String(length=16), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('avg_entry_price', sa.Float(), nullable=False),
    sa.Column('opened_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('portfolio_positions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_portfolio_positions_ticker_symbol'), ['ticker_symbol'], unique=False)

    op.create_table('tickers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('tier', sa.String(length=32), nullable=False),
    sa.Column('exchange', sa.String(length=32), nullable=False),
    sa.Column('sector', sa.String(length=64), nullable=True),
    sa.Column('industry', sa.String(length=128), nullable=True),
    sa.Column('float_shares', sa.Float(), nullable=True),
    sa.Column('shares_outstanding', sa.Float(), nullable=True),
    sa.Column('market_cap', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('reverse_split_count_3y', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tickers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tickers_symbol'), ['symbol'], unique=True)

    op.create_table('trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker_symbol', sa.String(length=16), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('executed_at', sa.DateTime(), nullable=False),
    sa.Column('prediction_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.create_index('ix_trades_ticker_executed', ['ticker_symbol', 'executed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_trades_ticker_symbol'), ['ticker_symbol'], unique=False)

    op.create_table('watchlist_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker_symbol', sa.String(length=16), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.Column('note', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('watchlist_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_watchlist_items_ticker_symbol'), ['ticker_symbol'], unique=True)

    op.create_table('backtest_trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('result_id', sa.Integer(), nullable=False),
    sa.Column('ticker_symbol', sa.String(length=16), nullable=False),
    sa.Column('entry_ts', sa.DateTime(), nullable=False),
    sa.Column('exit_ts', sa.DateTime(), nullable=True),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('pnl_pct', sa.Float(), nullable=True),
    sa.Column('exit_reason', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['result_id'], ['backtest_results.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('backtest_trades', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_backtest_trades_result_id'), ['result_id'], unique=False)

    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.create_index('ix_chat_messages_session_created', ['session_id', 'created_at'], unique=False)

    op.create_table('ohlcv_bars',
    sa.Column('ticker_id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('timeframe', sa.String(length=8), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('bid', sa.Float(), nullable=True),
    sa.Column('ask', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['ticker_id'], ['tickers.id'], ),
    sa.PrimaryKeyConstraint('ticker_id', 'ts', 'timeframe')
    )
    with op.batch_alter_table('ohlcv_bars', schema=None) as batch_op:
        batch_op.create_index('ix_ohlcv_ticker_ts', ['ticker_id', 'ts'], unique=False)

    op.create_table('predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker_symbol', sa.String(length=16), nullable=False),
    sa.Column('model_version_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('current_price', sa.Float(), nullable=False),
    sa.Column('liquidity_score', sa.Float(), nullable=False),
    sa.Column('manipulation_risk', sa.Float(), nullable=False),
    sa.Column('fundamental_score', sa.Float(), nullable=False),
    sa.Column('technical_score', sa.Float(), nullable=False),
    sa.Column('sentiment_score', sa.Float(), nullable=False),
    sa.Column('catalyst_score', sa.Float(), nullable=False),
    sa.Column('overall_ai_score', sa.Float(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('prob_up_5', sa.Float(), nullable=False),
    sa.Column('prob_up_10', sa.Float(), nullable=False),
    sa.Column('prob_up_20', sa.Float(), nullable=False),
    sa.Column('prob_downside_before_upside', sa.Float(), nullable=False),
    sa.Column('entry_zone_low', sa.Float(), nullable=False),
    sa.Column('entry_zone_high', sa.Float(), nullable=False),
    sa.Column('ideal_entry_price', sa.Float(), nullable=False),
    sa.Column('stop_loss', sa.Float(), nullable=False),
    sa.Column('take_profit_1', sa.Float(), nullable=False),
    sa.Column('take_profit_2', sa.Float(), nullable=False),
    sa.Column('take_profit_3', sa.Float(), nullable=False),
    sa.Column('max_allocation_pct', sa.Float(), nullable=False),
    sa.Column('risk_reward', sa.Float(), nullable=False),
    sa.Column('holding_period_days', sa.Integer(), nullable=False),
    sa.Column('explanation', sa.String(), nullable=False),
    sa.Column('horizon_probabilities', sa.JSON(), nullable=False),
    sa.Column('feature_snapshot', sa.JSON(), nullable=False),
    sa.Column('shap_top_factors', sa.JSON(), nullable=False),
    sa.CheckConstraint('confidence_score >= 0 AND confidence_score <= 100', name='ck_pred_confidence_band'),
    sa.CheckConstraint('current_price > 0', name='ck_pred_price_positive'),
    sa.CheckConstraint('holding_period_days > 0', name='ck_pred_horizon_positive'),
    sa.CheckConstraint('manipulation_risk >= 0 AND manipulation_risk <= 100', name='ck_pred_manip_band'),
    sa.CheckConstraint('overall_ai_score >= 0 AND overall_ai_score <= 100', name='ck_pred_overall_band'),
    sa.CheckConstraint('prob_downside_before_upside >= 0 AND prob_downside_before_upside <= 1', name='ck_pred_downside_unit'),
    sa.CheckConstraint('prob_up_10 >= 0 AND prob_up_10 <= 1', name='ck_pred_prob10_unit'),
    sa.CheckConstraint('prob_up_20 >= 0 AND prob_up_20 <= 1', name='ck_pred_prob20_unit'),
    sa.CheckConstraint('prob_up_5 >= 0 AND prob_up_5 <= 1', name='ck_pred_prob5_unit'),
    sa.CheckConstraint('stop_loss < ideal_entry_price AND ideal_entry_price < take_profit_1 AND take_profit_1 < take_profit_2 AND take_profit_2 < take_profit_3', name='ck_pred_level_ordering'),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_predictions_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_predictions_ticker_created', ['ticker_symbol', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_predictions_ticker_symbol'), ['ticker_symbol'], unique=False)

    op.create_table('outcomes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prediction_id', sa.Integer(), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(), nullable=False),
    sa.Column('horizon_days', sa.Integer(), nullable=False),
    sa.Column('realized_return_pct', sa.Float(), nullable=False),
    sa.Column('hit_take_profit_1', sa.Boolean(), nullable=False),
    sa.Column('hit_take_profit_2', sa.Boolean(), nullable=False),
    sa.Column('hit_take_profit_3', sa.Boolean(), nullable=False),
    sa.Column('hit_stop_loss', sa.Boolean(), nullable=False),
    sa.Column('max_drawdown_pct', sa.Float(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.CheckConstraint('horizon_days > 0', name='ck_outcome_horizon_positive'),
    sa.CheckConstraint('max_drawdown_pct <= 0', name='ck_outcome_drawdown_nonpositive'),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prediction_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('outcomes')
    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_predictions_ticker_symbol'))
        batch_op.drop_index('ix_predictions_ticker_created')
        batch_op.drop_index(batch_op.f('ix_predictions_created_at'))

    op.drop_table('predictions')
    with op.batch_alter_table('ohlcv_bars', schema=None) as batch_op:
        batch_op.drop_index('ix_ohlcv_ticker_ts')

    op.drop_table('ohlcv_bars')
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_index('ix_chat_messages_session_created')

    op.drop_table('chat_messages')
    with op.batch_alter_table('backtest_trades', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_backtest_trades_result_id'))

    op.drop_table('backtest_trades')
    with op.batch_alter_table('watchlist_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_watchlist_items_ticker_symbol'))

    op.drop_table('watchlist_items')
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trades_ticker_symbol'))
        batch_op.drop_index('ix_trades_ticker_executed')

    op.drop_table('trades')
    with op.batch_alter_table('tickers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tickers_symbol'))

    op.drop_table('tickers')
    with op.batch_alter_table('portfolio_positions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_portfolio_positions_ticker_symbol'))

    op.drop_table('portfolio_positions')
    with op.batch_alter_table('news_items', schema=None) as batch_op:
        batch_op.drop_index('ix_news_ticker_published')
        batch_op.drop_index(batch_op.f('ix_news_items_ticker_symbol'))
        batch_op.drop_index(batch_op.f('ix_news_items_published_at'))

    op.drop_table('news_items')
    op.drop_table('model_versions')
    with op.batch_alter_table('edgar_company_facts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_edgar_company_facts_ticker_symbol'))

    op.drop_table('edgar_company_facts')
    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_sessions_session_key'))

    op.drop_table('chat_sessions')
    op.drop_table('backtest_results')
    # ### end Alembic commands ###
