"""paper trading accounts and positions

Revision ID: 6f1d3edac330
Revises: 5b5ab8be5d21
Create Date: 2026-08-14 19:47:33.087495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f1d3edac330'
down_revision: Union[str, Sequence[str], None] = '5b5ab8be5d21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paper_trading_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('cash_balance', sa.Float(), nullable=False),
    sa.Column('starting_balance', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('paper_trading_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_paper_trading_accounts_user_id'), ['user_id'], unique=True)

    op.create_table('paper_positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('ticker_symbol', sa.String(length=16), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('avg_entry_price', sa.Float(), nullable=False),
    sa.Column('opened_at', sa.DateTime(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('realized_pnl_dollars', sa.Float(), nullable=True),
    sa.Column('entry_confidence_pct', sa.Float(), nullable=True),
    sa.Column('entry_risk_reward', sa.Float(), nullable=True),
    sa.Column('planned_stop_loss', sa.Float(), nullable=True),
    sa.Column('planned_take_profit', sa.Float(), nullable=True),
    sa.Column('risk_policy_version', sa.String(length=48), nullable=False),
    sa.Column('entry_data_source', sa.String(length=32), nullable=False),
    sa.Column('entry_data_mode', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['paper_trading_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('paper_positions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_paper_positions_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_paper_positions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_paper_positions_ticker_symbol'), ['ticker_symbol'], unique=False)

    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('position_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('data_source', sa.String(length=32), nullable=False, server_default='unknown'))
        batch_op.add_column(sa.Column('data_mode', sa.String(length=16), nullable=False, server_default='unspecified'))
        batch_op.create_index(batch_op.f('ix_trades_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trades_position_id'), ['position_id'], unique=False)
        batch_op.create_foreign_key('fk_trades_position_id', 'paper_positions', ['position_id'], ['id'])
        batch_op.create_foreign_key('fk_trades_account_id', 'paper_trading_accounts', ['account_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.drop_constraint('fk_trades_account_id', type_='foreignkey')
        batch_op.drop_constraint('fk_trades_position_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_trades_position_id'))
        batch_op.drop_index(batch_op.f('ix_trades_account_id'))
        batch_op.drop_column('data_mode')
        batch_op.drop_column('data_source')
        batch_op.drop_column('position_id')
        batch_op.drop_column('account_id')

    with op.batch_alter_table('paper_positions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_paper_positions_ticker_symbol'))
        batch_op.drop_index(batch_op.f('ix_paper_positions_status'))
        batch_op.drop_index(batch_op.f('ix_paper_positions_account_id'))

    op.drop_table('paper_positions')
    with op.batch_alter_table('paper_trading_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_paper_trading_accounts_user_id'))

    op.drop_table('paper_trading_accounts')
    # ### end Alembic commands ###
