"""signals and signal events

Revision ID: 7842891a0067
Revises: 9b1a60567a48
Create Date: 2026-07-12 16:28:41.131960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7842891a0067'
down_revision: Union[str, Sequence[str], None] = '9b1a60567a48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker_symbol', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('ideal_entry', sa.Float(), nullable=True),
    sa.Column('entry_zone_low', sa.Float(), nullable=True),
    sa.Column('entry_zone_high', sa.Float(), nullable=True),
    sa.Column('stop_loss', sa.Float(), nullable=True),
    sa.Column('targets', sa.JSON(), nullable=False),
    sa.Column('holding_period_days', sa.Integer(), nullable=True),
    sa.Column('risk_reward', sa.Float(), nullable=True),
    sa.Column('calibrated_probability', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('technical_score', sa.Float(), nullable=True),
    sa.Column('liquidity_score', sa.Float(), nullable=True),
    sa.Column('manipulation_risk', sa.Float(), nullable=True),
    sa.Column('dilution_risk_pct', sa.Float(), nullable=True),
    sa.Column('data_quality_score', sa.Float(), nullable=True),
    sa.Column('bullish_reasons', sa.JSON(), nullable=False),
    sa.Column('bearish_reasons', sa.JSON(), nullable=False),
    sa.Column('invalidation_conditions', sa.JSON(), nullable=False),
    sa.Column('rejection_reasons', sa.JSON(), nullable=False),
    sa.Column('data_source', sa.String(length=48), nullable=False),
    sa.Column('data_mode', sa.String(length=16), nullable=False),
    sa.Column('model_version', sa.String(length=48), nullable=False),
    sa.Column('feature_version', sa.String(length=48), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('signals', schema=None) as batch_op:
        batch_op.create_index('ix_signals_ticker_created', ['ticker_symbol', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_signals_ticker_symbol'), ['ticker_symbol'], unique=False)

    op.create_table('signal_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('signal_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('from_status', sa.String(length=24), nullable=True),
    sa.Column('to_status', sa.String(length=24), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('signal_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_signal_events_signal_id'), ['signal_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('signal_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_signal_events_signal_id'))

    op.drop_table('signal_events')
    with op.batch_alter_table('signals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_signals_ticker_symbol'))
        batch_op.drop_index('ix_signals_ticker_created')

    op.drop_table('signals')
    # ### end Alembic commands ###
