"""scan history and outcome max_runup

Revision ID: 98ca21252e8b
Revises: 6bbad53f77a7
Create Date: 2026-07-11 19:29:49.179258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98ca21252e8b'
down_revision: Union[str, Sequence[str], None] = '6bbad53f77a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scan_cycles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('provider_name', sa.String(length=32), nullable=False),
    sa.Column('universe_size', sa.Integer(), nullable=False),
    sa.Column('accepted_count', sa.Integer(), nullable=False),
    sa.Column('rejected_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scan_cycles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scan_cycles_started_at'), ['started_at'], unique=False)

    op.create_table('scan_decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=False),
    sa.Column('ticker_symbol', sa.String(length=16), nullable=False),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('ai_score', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('manipulation_risk', sa.Float(), nullable=True),
    sa.Column('reasons', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['cycle_id'], ['scan_cycles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scan_decisions', schema=None) as batch_op:
        batch_op.create_index('ix_scan_decisions_cycle_decision', ['cycle_id', 'decision'], unique=False)
        batch_op.create_index('ix_scan_decisions_ticker', ['ticker_symbol'], unique=False)

    with op.batch_alter_table('outcomes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_runup_pct', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outcomes', schema=None) as batch_op:
        batch_op.drop_column('max_runup_pct')

    with op.batch_alter_table('scan_decisions', schema=None) as batch_op:
        batch_op.drop_index('ix_scan_decisions_ticker')
        batch_op.drop_index('ix_scan_decisions_cycle_decision')

    op.drop_table('scan_decisions')
    with op.batch_alter_table('scan_cycles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scan_cycles_started_at'))

    op.drop_table('scan_cycles')
    # ### end Alembic commands ###
