"""users and ownership

Revision ID: 9b1a60567a48
Revises: 98ca21252e8b
Create Date: 2026-07-12 09:44:22.071149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b1a60567a48'
down_revision: Union[str, Sequence[str], None] = '98ca21252e8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('token_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_chat_sessions_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key('fk_chat_sessions_user_id', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('portfolio_positions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_portfolio_positions_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key('fk_portfolio_positions_user_id', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('watchlist_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_watchlist_items_ticker_symbol'))
        batch_op.create_index(batch_op.f('ix_watchlist_items_ticker_symbol'), ['ticker_symbol'], unique=False)
        batch_op.create_index(batch_op.f('ix_watchlist_items_user_id'), ['user_id'], unique=False)
        batch_op.create_unique_constraint('uq_watchlist_user_ticker', ['user_id', 'ticker_symbol'])
        batch_op.create_foreign_key('fk_watchlist_items_user_id', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watchlist_items', schema=None) as batch_op:
        batch_op.drop_constraint('fk_watchlist_items_user_id', type_='foreignkey')
        batch_op.drop_constraint('uq_watchlist_user_ticker', type_='unique')
        batch_op.drop_index(batch_op.f('ix_watchlist_items_user_id'))
        batch_op.drop_index(batch_op.f('ix_watchlist_items_ticker_symbol'))
        batch_op.create_index(batch_op.f('ix_watchlist_items_ticker_symbol'), ['ticker_symbol'], unique=1)
        batch_op.drop_column('user_id')

    with op.batch_alter_table('portfolio_positions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_portfolio_positions_user_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_portfolio_positions_user_id'))
        batch_op.drop_column('user_id')

    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_chat_sessions_user_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_chat_sessions_user_id'))
        batch_op.drop_column('user_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
