"""unified multi-asset registry

Revision ID: cf153aaf7ad5
Revises: 7842891a0067
Create Date: 2026-08-05 20:06:57.609557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf153aaf7ad5'
down_revision: Union[str, Sequence[str], None] = '7842891a0067'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('asset_type', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('exchange', sa.String(length=32), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('tradable', sa.Boolean(), nullable=False),
    sa.Column('trading_hours', sa.String(length=64), nullable=False),
    sa.Column('data_delay', sa.String(length=32), nullable=False),
    sa.Column('supported_timeframes', sa.JSON(), nullable=False),
    sa.Column('otc_tier', sa.String(length=32), nullable=True),
    sa.Column('otc_caveat_emptor', sa.Boolean(), nullable=True),
    sa.Column('otc_shell_risk', sa.Boolean(), nullable=True),
    sa.Column('otc_disclosure_status', sa.String(length=32), nullable=True),
    sa.Column('otc_reverse_split_count_3y', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assets_asset_type'), ['asset_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_symbol'), ['symbol'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assets_symbol'))
        batch_op.drop_index(batch_op.f('ix_assets_asset_type'))

    op.drop_table('assets')
    # ### end Alembic commands ###
